/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.gt.homeNas.application;

import com.google.common.cache.Cache;
import com.google.common.cache.CacheBuilder;
import com.google.common.cache.CacheLoader;
import com.gt.homeNas.domain.entity.User;
import com.gt.homeNas.types.UserAccount;
import com.gt.homeNas.types.UserId;
import com.gt.homeNas.types.UserName;
import com.gt.homeNas.types.UserPasswd;
import com.gt.homeNas.types.exception.UserAccountInvalidError;
import com.gt.homeNas.types.exception.UserPasswdInvalidError;
import javafx.application.Application;
import javafx.fxml.FXMLLoader;
import javafx.scene.Parent;
import javafx.scene.Scene;
import javafx.stage.Modality;
import javafx.stage.Stage;
import javafx.stage.StageStyle;

import java.util.HashMap;
import java.util.Map;
import java.util.Objects;

public class App extends Application {



    @Override
    public void start(Stage primaryStage) throws Exception {
        Parent loginPage = FXMLLoader.load(Objects.requireNonNull(getClass().getResource("/controller/login.fxml")));
        Scene loginScene = new Scene(loginPage);
        primaryStage.setScene(loginScene);
        primaryStage.setTitle("用户登录");
        primaryStage.setScene(loginScene);
        primaryStage.show();
    }
}
